'use strict';
const fullName = 'Noah Khayat';
console.log('value of full name:', fullName);
const isCool = true;
console.log('value isCool:', isCool);
const TotalPet = 1000;
console.log('the value of totalPet', TotalPet);
console.log('typeof fullName:', typeof fullName);
console.log('typeof isCool:', typeof isCool);
console.log('typeof TotalPet:', typeof TotalPet);
const empty = null;
console.log('the value of empty', empty);
console.log('typeof of empty', typeof empty);
let nothing;
console.log('the value of nothing', nothing);
console.log('typeof of nothing', typeof nothing);
